name: pharma_inc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  flutter_gen_runner: ^5.1.0+1
  build_runner: ^2.3.3

flutter_gen:
  output: lib/generated
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  gen_watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean:
    - flutter clean
    - flutter pub get
    - flutter pub upgrade
    - derry gen
  test: flutter test --coverage
  update:
    - flutter pub get
    - flutter pub upgrade